server:
  port: 18003

spring:
  application:
    name: zookeeper-service
  cloud:
    zookeeper:
      connect-string: localhost:2182
      discovery:
        enabled: true  # 关闭服务发现，否则启动会报异常

logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN
