server:
  port: 18001
spring:
  application:
    name: zuul-web-a # 此实例注册到eureka服务端的name
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

# 服务管理
eureka:
  client:
    service-url:
      defaultZone: http://localhost:16000/eureka/
  instance:
    prefer-ip-address: true # 是否显示Ip地址: 是否使用 ip 地址注册
#    instance-id: zuul-web-a-0 # 此实例注册到eureka服务端的唯一的实例ID
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
    #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    lease-renewal-interval-in-seconds: 30
    #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
    lease-expiration-duration-in-seconds: 90
