server:
  port: 18002   #端口号

spring:
  application:
    name: eureka-client   # 服务名称

eureka:
  client:
    service-url:
      registerWithEureka: false # 默认true，关闭自我注册，默认情况下，服务中心也会作为客户端来自己注册自己
      defaultZone: http://localhost:16000/eureka/  # 服务注册中心的地址

# OpenFeign (可选配置,都不是必须的，默认就行)
feign:
  client:
    config:
      default:
        connectTimeout: 5000  # 指定Feign客户端连接提供者的超时时限   取决于网络环境
        readTimeout: 5000     # 指定Feign客户端从请求到获取到提供者给出的响应的超时时限  取决于业务逻辑运算时间
  compression:
    request:
      enabled: true  # 是否对请求进行GZIP压缩
      mime-types: text/xml,application/xml,application/json  # 指定压缩的请求数据类型
      min-request-size: 2048  # 超过该大小的请求会被压缩
    response:
      enabled: true  # 是否对响应进行GZIP压缩
  hystrix:
    enabled: false   # 在Feign中开启Hystrix，默认false关闭，要使用fallback功能这里必须启用
# OpenFeign 特定类指定特定日志级别：
logging:
  level:
    com.zja.client.ServiceOpenFeign: debug   # 修改日志级别 NONE、BASIC、HEADERS、FULL

#  NONE，无记录（DEFAULT）。
#  BASIC，只记录请求方法和URL以及响应状态代码和执行时间。
#  HEADERS，记录基本信息以及请求和响应标头。
#  FULL，记录请求和响应的头文件，正文和元数据。 推荐使用