server:
  port: 18002
  servlet:
    context-path: /b
spring:
  application:
    name: gateway-web-b
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

# 服务管理
eureka:
  client:
    service-url:
      defaultZone: http://localhost:16000/eureka/
