server:
  port: 8081
spring:
  application:
    name: web

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/  # 服务注册中心的地址


# 日志打印级别
logging:
  level:
    com.zja.service.feign.HelloWorldService: debug   # OpenFeign 给特定类指定日志级别
    org.apache.zookeeper.ClientCnxn: WARN    # zookeeper 注册中心日志级别

#  NONE，无记录（DEFAULT）。
#  BASIC，只记录请求方法和URL以及响应状态代码和执行时间。
#  HEADERS，记录基本信息以及请求和响应标头。
#  FULL，记录请求和响应的头文件，正文和元数据。 推荐使用