server:
  port: 18005  # 服务指定的端口

spring:
  application:
    name: config-server  # 指定服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengjiaao/springcloud-test-root.git  #配置文件所在仓库
          username: zhengjiaao       # git仓库的账号
          password: jia15837866351   # git仓库的密码
          search-paths: /cloud-config/config-catalog/   # git仓库地址下的相对地址 多个用逗号","分割。
          default-label: master      # 配置文件分支，默认master
