server:
  port: 8084
spring:
  application:
    name: gateway-web
  #redis配置
#  redis:
#    host: 192.168.159.128  # 虚拟机 docker redis
#    port: 6379
#    database: 0
  #开启热部署
  devtools:
    restart:
      enabled: true
  #网关配置
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # 网关静态路由配置
      routes:
        - id: gateway_route
          uri: http://127.0.0.1:8082
          order: 1
          predicates: # 断言，当路由满足全部断言时进行转发
            - Path=/web/**
          filters:  # 过滤器
            - StripPrefix=1 # 删除一级路径
#          filters:
#            #- RewritePath=/(?<segment>.*),/$\{segment}  # 拦截器
#            - name: RequestRateLimiter
#              args:
#                key-resolver: '#{@uriKeyResolver}'
#                redis-rate-limiter.replenishRate: 1  # 每秒钟向redis注册一个令牌
#                redis-rete-limiter.burstCapacity: 2  # 每秒最多访问2次
#      discovery:  # 发现服务-目的实现动态路由配置
#        locator:
#          enabled: true

# 动态路由配置
# 设置注册中心地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka/  # 服务注册中心的地址


# 日志打印级别
logging:
  level:
    com.zja.service.feign.HelloWorldService: debug   # OpenFeign 给特定类指定日志级别
    org.apache.zookeeper.ClientCnxn: WARN    # zookeeper 注册中心日志级别

#  NONE，无记录（DEFAULT）。
#  BASIC，只记录请求方法和URL以及响应状态代码和执行时间。
#  HEADERS，记录基本信息以及请求和响应标头。
#  FULL，记录请求和响应的头文件，正文和元数据。 推荐使用