server:
  port: 18000
spring:
  application:
    name: gateway
  #开启热部署
  devtools:
    restart:
      enabled: false
  #网关配置
  cloud:
    gateway:
      routes:
        - id: time_route  # 通过时间匹配 after_route
          uri: http://127.0.0.1:18001
          predicates:
            - After=2020-11-01T06:06:06+08:00[Asia/Shanghai]  # 设置只有在2020年11月02日才会转发到我的网站
#            - Between=2018-01-20T06:06:06+08:00[Asia/Shanghai], 2019-01-20T06:06:06+08:00[Asia/Shanghai]

#      routes:
#        - id: cookie_route  # 通过cokkie匹配
#          uri: http://ityouknow.com
#          predicates:
#            - Cookie=ityouknow, kee.e
# curl 测试，命令行输入:
# curl http://localhost:8080 --cookie "ityouknow=kee.e"








# 服务管理
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:16000/eureka/