server:
  port: 8081
  servlet:
    context-path: /oa  # 一定要配置，不能配置为 /

spring:
  application:
    name: oa application
    version: 1.0

security:
  oauth2:
    client: # 表示 是一个OAuth2客户端，用户获取token
      client-id: oa_client
      client-secret: oa_secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      jwt:
        key-uri: http://localhost:8080/oauth/token_key # 用于获取 tokenKey，进行全面解析 token

qq:
  profile-uri: http://localhost:8082/qq/profile


logging:
  level:
    org.springframework.security: DEBUG
