server:
  port: 18001
spring:
  application:
    name: gateway-web-a
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

# 服务管理
eureka:
  client:
    service-url:
      defaultZone: http://localhost:16000/eureka/