# spring.cloud.stream.bindings.[output].destination:         交换机的名称
# spring.cloud.stream.bindings.[output].group:               组，用于生成队列，组名相同时可以实现分布式
# spring.cloud.stream.bindings.[input].destination:          交换机的名称
# spring.cloud.stream.bindings.[input].group:                组，用于生成队列，组名相同时可以实现分布式
# spring.cloud.stream.bindings.[input].consumer.concurrency: 消费者的并发量
# spring.rabbitmq.addresses:                                 服务器地址
# spring.rabbitmq.username:                                  账号
# spring.rabbitmq.password:                                  密码
# spring.rabbitmq.virtual-host:                              虚拟主机


# output: 相当于生产者producer，它是从队列中发送消息的
# input:  相当于消费者consumer，它是从队列中接收消息的

spring:
  stream:
    default-binder: rabbit
    bindings:
      #使用系统默认的两个管道output、input
      output:
        destination: order.exchange
        group: order.queue
      input:
        destination: order.exchange
        group: order.queue
        consumer:
          concurrency: 3
  rabbitmq:
    addresses: 192.168.200.100:5672
    username: rabbit
    password: 123456
    virtual-host: /
